"use client";

import { useEffect, useState } from "react";
import { useUser } from "@clerk/nextjs";
import { useRouter } from "next/navigation";
import { Card } from "@/components/ui/card";
import DashboardLayout from "../_components/DashboardLayout";

const ADMIN_EMAIL = "rithikashree76@gmail.com";

export default function AdminDashboardPage() {
  const { user, isLoaded } = useUser();
  const router = useRouter();
  const [history, setHistory] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!isLoaded) return;

    const email = user?.primaryEmailAddress?.emailAddress;

    // Client-side protection
    if (!user || email !== ADMIN_EMAIL) {
      router.replace("/dashboard");
      return;
    }

    const fetchAllHistory = async () => {
      try {
        const res = await fetch("/api/admin/history");
        if (!res.ok) {
          throw new Error("Failed to fetch admin history");
        }
        const data = await res.json();
        setHistory(data.history || []);
      } catch (err: any) {
        setError(err.message);
      } finally {
        setLoading(false);
      }
    };

    fetchAllHistory();
  }, [user, isLoaded, router]);

  if (!isLoaded || loading) {
    return (
      <DashboardLayout>
        <div className="flex items-center justify-center min-h-screen">
          <p className="text-gray-500 text-xl animate-pulse">Loading Admin Panel...</p>
        </div>
      </DashboardLayout>
    );
  }

  if (error) {
    return (
      <DashboardLayout>
        <div className="p-8 text-center text-red-500">
          <h1 className="text-2xl font-bold mb-4">Error</h1>
          <p>{error}</p>
        </div>
      </DashboardLayout>
    );
  }

  return (
    <DashboardLayout>
      <main className="p-6 bg-gray-50 min-h-screen">
        <div className="mb-8">
          <h1 className="text-3xl font-bold text-purple-800">Global Admin Dashboard</h1>
          <p className="text-gray-600 mt-2">Viewing all generations from all users across the platform.</p>
        </div>

        {history.length === 0 ? (
          <div className="text-center p-12 bg-white rounded-xl shadow-sm border border-gray-200">
            <p className="text-gray-500 text-lg">No images have been generated by anyone yet.</p>
          </div>
        ) : (
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
            {history.map((item, index) => (
              <Card key={index} className="overflow-hidden bg-white shadow-md hover:shadow-lg transition">
                <img src={item.url} alt={item.prompt} className="w-full h-48 object-cover rounded-t-lg" />
                <div className="p-4">
                  <p className="text-sm font-semibold text-gray-800 mb-2 truncate" title={item.prompt}>
                    {item.prompt}
                  </p>
                  <p className="text-xs text-purple-600 font-mono mb-1 truncate" title={item.user_id}>
                    User: {item.user_id}
                  </p>
                  <a
                    href={`/api/download?url=${encodeURIComponent(item.url)}&filename=${encodeURIComponent(`${item.prompt.toLowerCase().replace(/\s+/g, "_")}.png`)}`}
                    className="block mt-4 text-sm text-purple-600 hover:underline font-medium"
                  >
                    ⬇️ Download Image
                  </a>
                  <p className="text-xs text-gray-400">
                    {new Date(item.timestamp).toLocaleString()}
                  </p>
                </div>
              </Card>
            ))}
          </div>
        )}
      </main>
    </DashboardLayout>
  );
}
